### ISSUE TITLE
Music Identifies various module/tracker file formats (it, mod, s3m, etc.) as corrupt. [$10]

### ISSUE THREAD

**Issue by Zachs-Kappler** [elementary/music#455]
In my music folder I have a few folders of chiptune files from various sites as well as many modules from The Mod Archive. Every time I try to use Music or add to my library, it shows a prompt to delete the "corrupted music files" it found, but they are actually playable in other programs like Audacious, Clementine, and even MilkyTracker.

The best solution would be to either add support for these formats, or have Music ignore them.

To replicate this issue, go grab some tracker music files from The Mod Archive, Project2612 or similar sites and put them into your Music folder. Upon starting Music, try to import them.

Music (noise 5.0+r2573+pkg110~ubuntu5.0.1)
Elementary OS Juno

**Comment by eljefuri** [comment]
If support is added, I recommend [libxmp](http://xmp.sourceforge.net/) as the playback library. It is the most most accurate one that I know of, with the broadest support.

**Comment by Mohelm97** [comment]
Soo Musics uses GStreamer, and you can easily install "gstreamer1.0-plugins-bad"
So just type: "sudo apt install gstreamer1.0-plugins-bad" and here you go playing it, mod, s3m, and more. (I've tested the 3 mentioned formats and it works like a charm)
![image](https://user-images.githubusercontent.com/1688821/49101932-579d0500-f26f-11e8-9c16-5bce25a52851.png)

I don't deserve a bounty XD

**Comment by Mohelm97** [comment]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-modplug.html
More info if you want.

**Comment by Mohelm97** [comment]
Hi all, I've deleted my previous comments because I found a problem in importing them to the library,
So here we go again :D
First to make them playable just install "gstreamer1.0-plugins-bad"
The second part is about the library, (it. mod) files imported normally to the library but this is not the case for s3m.
If I added the s3m to the library then I will get the Bounty? XD

**Comment by Mohelm97** [comment]
So yeah s3m wasn't added to the content_types list,
Everything works fine 
![image](https://user-images.githubusercontent.com/1688821/49104067-fa0bb700-f274-11e8-87f0-6d4d571cf2b1.png)
However metadata wasn't loaded right (As I see them in Kid3), and this thing isn't something we can do anything about here.
You can always edit metadata in the Music app instated and have them organised ;)

**Comment by Zachs-Kappler** [comment]
Can the same be done for the following tracker/chiptune formats?

- [ ] MiniUSF (N64)
- [ ] SPC (SNES)
- [ ] NSF (NES)
- [ ] VGM/VGZ (Genesis/32X/MasterSystem)
- [ ] PSF (PS1)
- [ ] Mini2SF (NDS)
- [ ] MiniGSF (GBA)
- [ ] GBS (GB/GBC)
- [ ] SID (Commodore)
- [ ] FTM (FamiTracker)

**Comment by Mohelm97** [comment]
@Zachs-Kappler I will try and get some of these files and update the list if there's support in GStreamer

**Comment by Zachs-Kappler** [comment]
I wouldn't really call this closed since only one of the misidentified formats was fixed with that pull request. There are more tracker/chiptune formats than just it, mod, and s3m. There was an "etc." at the end of that list for a reason.

**Comment by Mohelm97** [comment]
I'm kinda with you but not totally, the other types you mentioned are so specific and no actual player will care about playing them :( and there's no support for them in GStreamer :(

**Comment by Zachs-Kappler** [comment]
Can the rest be blacklisted then?
